// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwvnsJi0AQqdWo19CZ8mgA-qpGQirk3bw',
    appId: '1:769606657768:web:6219e1025c3e2a5e714b5d',
    messagingSenderId: '769606657768',
    projectId: 'sejadah-crm-app',
    authDomain: 'sejadah-crm-app.firebaseapp.com',
    storageBucket: 'sejadah-crm-app.firebasestorage.app',
    measurementId: 'G-MRYDECJYJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFs62v2BVr1ldU7q4sal6oJ0cBFcObCL4',
    appId: '1:769606657768:android:948439370e3cf47f714b5d',
    messagingSenderId: '769606657768',
    projectId: 'sejadah-crm-app',
    storageBucket: 'sejadah-crm-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwvnsJi0AQqdWo19CZ8mgA-qpGQirk3bw',
    appId: '1:769606657768:web:5d290d77a773274e714b5d',
    messagingSenderId: '769606657768',
    projectId: 'sejadah-crm-app',
    authDomain: 'sejadah-crm-app.firebaseapp.com',
    storageBucket: 'sejadah-crm-app.firebasestorage.app',
    measurementId: 'G-FBX8CF67WB',
  );
}
